//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exort.NativeLibraries.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exort.NativeLibraries.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library loaded successfully, {0}.
        /// </summary>
        internal static string LibraryLoadedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("LibraryLoadedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library loading failed, {0}, {1}.
        /// </summary>
        internal static string LibraryLoadFailedMessage {
            get {
                return ResourceManager.GetString("LibraryLoadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library loading started, {0}.
        /// </summary>
        internal static string LibraryLoadingStartedMessage {
            get {
                return ResourceManager.GetString("LibraryLoadingStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library methods loading started, {0}.
        /// </summary>
        internal static string LibraryMethodsLoadingStartedMessage {
            get {
                return ResourceManager.GetString("LibraryMethodsLoadingStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library path cannot be null or empty, {0}.
        /// </summary>
        internal static string LibraryNullOrEmptyPathMessage {
            get {
                return ResourceManager.GetString("LibraryNullOrEmptyPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library unload falied, {0}. {1}.
        /// </summary>
        internal static string LibraryUnloadFailedMessage {
            get {
                return ResourceManager.GetString("LibraryUnloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library cannot be unload, {0}.
        /// </summary>
        internal static string LibraryUnloadNotFoundMessage {
            get {
                return ResourceManager.GetString("LibraryUnloadNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library unload successfully, {0}.
        /// </summary>
        internal static string LibraryUnloadSuccessfullyMessage {
            get {
                return ResourceManager.GetString("LibraryUnloadSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method cannot be loaded with this delegate type, {0}, {1}.
        /// </summary>
        internal static string MethodBadDelegateTypeMessage {
            get {
                return ResourceManager.GetString("MethodBadDelegateTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to load an unloaded library method, {0}, {1}.
        /// </summary>
        internal static string MethodLoadAnUnloadedLibraryMessage {
            get {
                return ResourceManager.GetString("MethodLoadAnUnloadedLibraryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method loaded successfullty, {0}, {1}.
        /// </summary>
        internal static string MethodLoadedSuccessfulltyMessage {
            get {
                return ResourceManager.GetString("MethodLoadedSuccessfulltyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method loading started, {0}, {1}.
        /// </summary>
        internal static string MethodLoadingStartedMessage {
            get {
                return ResourceManager.GetString("MethodLoadingStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not found in library, {0}, {1}.
        /// </summary>
        internal static string MethodNotFoundMessage {
            get {
                return ResourceManager.GetString("MethodNotFoundMessage", resourceCulture);
            }
        }
    }
}
